apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx

bases:
  - ../../application

patches:
  - replica_count.yaml

images:
  - name: nginx
    newTag: stable

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.properties
